export class Product {
    id!:number;
    productId!: String;
    nature!: String;
    nomProduit!   :               String;
    typeProduit!: String;
    familleOption!  :              String;
    tarifParDefaut! :             String;
    tarifHT   !      :             number;
    tarifTTC  !      :             number;
    coutDeRevient!   :            number;
    montant!          :             number;
    offerShdes!       :            String;
    offerValue  !     :            String;
    serviceShdes !     :           String;
    packageShdes !     :           String;
    parameterShdes!    :           String;
    parameterValue !    :          String;
    parameterValueDes! :         String;
    parameterNo  !        :        number;
    faxIsMandatory !    :         String;
    apnIsMandatory  !  :          String;
    crmArpuOut   !      :         String;
    crmArpuIn    !       :        String;
    crmCoutDirect   !     :       String;
    crmCoutExploitation !:        String;
    crmCoutAcquisition  !  :      String;
    crmForfaitHtHorsRecharge! : String;
    crmRecharge !            :     String;
    crmBudgetSubvention12! :     String;
    crmBudgetSubvention24 !:     String;
    crmBudgetSubvention36 ! :    String;
}
